### ISSUE TITLE
Crash in production mode using withTheme without ThemeProvider

### ISSUE THREAD

**Issue by Dema** [styled-components/styled-components#1709]
## Environment

`npx envinfo --system --binaries --npmPackages styled-components,babel-plugin-styled-components --markdown --clipboard`
Environment:
  OS:  Linux 4.16
  Node:  8.11.1
  Yarn:  1.3.2
  npm:  5.6.0
  Watchman:  Not Found
  Xcode:  N/A
  Android Studio:  Not Found

## Steps to reproduce

1) Use withTheme HOC without wrapping application in ThemeProvider on production build

## Actual Behavior
Crashes with
```
styled-components.browser.es.js:2137 Uncaught (in promise) TypeError: Cannot read property 'subscribe' of undefined
    at n.componentWillMount (styled-components.browser.es.js:2137)
    at mountClassInstance (react-dom.production.min.js:112)
```
There is a code in `styled-components/src/hoc/withTheme.js `

```javascript
    componentWillMount() {
      const { defaultProps } = this.constructor
      const styledContext = this.context[CHANNEL_NEXT]
      const themeProp = determineTheme(this.props, undefined, defaultProps)
      if (
        styledContext === undefined &&
        themeProp === undefined &&
        process.env.NODE_ENV !== 'production'
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      ) {
        // eslint-disable-next-line no-console
        console.warn(
          '[withTheme] You are not using a ThemeProvider nor passing a theme prop or a theme in defaultProps'
        )
      } else if (styledContext === undefined && themeProp !== undefined) {
        this.setState({ theme: themeProp })
      } else {
        const { subscribe } = styledContext
        this.unsubscribeId = subscribe(nextTheme => {
          const theme = determineTheme(this.props, nextTheme, defaultProps)
          this.setState({ theme })
        })
      }
    }
```
If I don't wrap my app in ThemeProvider while in development environment it shows warning 'You are not using a ThemeProvider', BUT if you are in the production mode, this condition is false and we end up in else branch where it crashes trying to access subscribe on styledConted which is undefined.

**Comment by deehuey** [comment]
Uhm... just curious why you'd use `withTheme` without the provider? That's like trying to use connect without redux...

**Comment by Dema** [comment]
I don't, but `reflex` library, that I use, does. Actually, we were using themes, but decided to get rid of them.

**Comment by eddiesholl** [comment]
Yeah, I feel like the warning you see when this occurs in dev mode needs to be more scary. I was not expecting the chance of a hard failure with a prod build.

**Comment by probablyup** [comment]
I think we can probably take a look at softening this for 4.0.

**Comment by Dema** [comment]
The issue is not with warnings but with wrong if condition. 
```javascript
styledContext === undefined &&
        themeProp === undefined &&
        process.env.NODE_ENV !== 'production'
```
it should be 

```javascript
if (styledContext === undefined && themeProp === undefined) {
  if (process.env.NODE_ENV !== "production") {
    // eslint-disable-next-line no-console
    console.warn(
      "[withTheme] You are not using a ThemeProvider nor passing a theme prop or a theme in defaultProps"
    );
  }
}
```

**Comment by 5id** [comment]
+1

The tests that currently assert that the behaviour in #1130 are misleading - https://github.com/styled-components/styled-components/blob/master/src/test/theme.test.js#L465 - as they pass because NODE_ENV is not set to production.

But if you set NODE_ENV to production, they start to fail.

It'd be great to see this fixed before 4.0, or if you're happy with the fix above ^ then I'll be happy to raise a PR.
---
Currently this is bad because the only way to render components that get wrapped in withTheme, is to do something like:
```
const ThemedComponent = withTheme(Component);
const SafeThemedComponent = (props = {}) => (
  <ThemeProvider theme={{}} >
    <ThemedComponent {...props} />
  </ThemeProvider>
);
```

This forces us to render an extra unnecessary ThemeProvider every time :(

**Comment by ghalex** [comment]
I have same issue here trying to create a HOC :

```
const withVariant = (key) => BaseComponent => {
  class WithVariant extends React.Component {
    render () {
      let { variant, theme } = this.props
      let variantProps = {}

      if (variant && theme && theme.components[key] && theme.components[key][variant]) {
        variantProps = theme.components[key][variant]
      }

      return (
        <BaseComponent {...this.props} {...variantProps} />
      )
    }
  }

  return compose(
    setWrappedDisplayName('withVariant')
  )(WithVariant)
}
```

Any suggestions on how to use this without a theme ? As you can see I check if the theme prop exist but the withTheme hoc then crush in production.

**Comment by probablyup** [comment]
This is fixed in v4

**Comment by Dema** [comment]
The bug is still not fixed, maybe just hidden. The actual bug is not with absent theme but with wrong condition that fails in production mode. https://github.com/styled-components/styled-components/blob/master/src/hoc/withTheme.js#L38 If `styledContext = undefined,  themeProp = undefined, process.env.NODE_ENV = 'production'` this code will still fail.

**Comment by Dema** [comment]
Yep, sorry, I assumed that master has the most recent changes. Thank you for your hard work! styled-components are amazing! :)
