### ISSUE TITLE
styles passed into styled(Component) don't overwrite base styles

### ISSUE THREAD

**Issue by SilencerWeb** [styled-components/styled-components#1816]
## Environment
`npx envinfo --system --binaries --npmPackages styled-components,babel-plugin-styled-components --markdown --clipboard` - zsh: command not found: npx

## Reproduction
https://codesandbox.io/s/k51yyo4v35

Heading.js
```jsx
import * as React from "react";
import styled, { css } from "styled-components";

const Wrapper = styled.h1`
  margin-top: 0;
  margin-bottom: 0;
`;

export const Heading = props => {
  const WrapperWithAnotherTag = props.tag && props.tag !== "h1"
      ? Wrapper.withComponent(props.tag) : Wrapper;

  return (
    <WrapperWithAnotherTag className={props.className}>
      {props.children}
    </WrapperWithAnotherTag>
  );
};
```

Index.js
```jsx
import React from "react";
import ReactDOM from "react-dom";
import styled, { css } from "styled-components";

import { Heading } from "./heading";

const Name = styled(Heading)`
  margin-bottom: 10px;
`;

function App() {
  return (
    <div className="App">
      <Name>Here is a title with margin</Name>
      <Name tag={"h2"}>Here is a title without margin -_-</Name>
    </div>
  );
}

const rootElement = document.getElementById("root");
ReactDOM.render(<App />, rootElement);
```

## Expected Behavior
```jsx
<Name tag={"h2"}>Here is a title without margin -_-</Name>
```
should have margin-bottom

## Actual Behavior
```jsx
<Name tag={"h2"}>Here is a title without margin -_-</Name>
```
Doesn't have margin-bottom because it doesn't overwrite base styles

P.S. it is simplified example!

**Comment by probablyup** [comment]
Alright so the issue here is related to the order of composed classNames. If you inspect the H2, the CSS for `margin-bottom: 10px` is there but is being overridden by the base component styles due to how s-c is composing the passed class name vs the class name it injects itself.

@kitten @mxstbr do you guys remember why we put the SC classnames last instead of first?

**Comment by stonebk** [comment]
I just ran into this and while I understand the cause and the solution, the solution feels like a workaround for unexpected behavior. I would expect that styles for an extended component always follow the styles of the base component -- that's the whole point of extending.

**Comment by littlefinger42** [comment]
I agree with @stonebk . This should be default behaviour and this issue should be reopened.

**Comment by jtiscione** [comment]
The "&&" trick is no help.

If I use regular CSS, or style tags, I can set the style, but if I use styled-components the styles get overridden for some reason even if I use "!important". This is with hardly anything else on the page.

**Comment by dblundellRH** [comment]
Agree, this seems like odd behaviour.

**Comment by kraizybone** [comment]
This seems to work as expected in v3. After I updated to v4 styles doesn't applies in right order. This should be reopen.

**Comment by thismarcoantonio** [comment]
What is the current state of this?

**Comment by alanford123** [comment]
I still have this issue, specifically with a third party styled components framework. (react-bulma-components)

**Comment by teseo** [comment]
Still happening here

**Comment by RellaxxDev** [comment]
Still happening and does not fixed in 4.2.1
Why issue is closed?

**Comment by kitten** [comment]
@RellaxxDev this issue is resolved. We still maintain specificity as we have always in all versions which is now going to be improved in v5.

Anyway, in the example withComponent is called dynamically during the runtime. This creates a new StyledComponent on every render. Since we order by creation order that does mean that after creating a new component the order will be the opposite of what the CodeSandbox here expects.

We introduced the "as" prop to solve this.

**Comment by Sotir-Akkroo** [comment]
Is this "resolved" means to be in v5? Problem still occurs on 4.3.2. Thanks!

**Comment by GermaVinsmoke** [comment]
Not working, even with `&&`

**Comment by hboylan** [comment]
The solution that worked for me was to pass the `className` prop into the styled component you wish to override. Thanks [StackOverflow](https://stackoverflow.com/questions/51636412/styled-components-not-overriding-styles-from-another-component)!

**Comment by tavurth** [comment]
> The solution that worked for me was to pass the `className` prop into the styled component you wish to override. Thanks [StackOverflow](https://stackoverflow.com/questions/51636412/styled-components-not-overriding-styles-from-another-component)!

That's a different issue. The above issue is understanding that you can pass a class name into the component, the issue arises when we have multiple levels of class names of the same specificity.

Example follows:

```javascript
const ComponentA = styled.div`
  width: 100%;
  height: 100%;
`

function ExtendedComponent({ className }) {
  return <ComponentA className={className} />
}

const StyledExtendedComponent = styled(ExtendedComponent)`
  width: 50%;
`
```

`width: 50%` will not be applied in this case.
`width: 100%` will be applied.

To fix the issue we currently have to use:

```javascript
const StyledExtendedComponent = styled(ExtendedComponent)`
  && {
    width: 50%;
  }
`
```

This really seems like a bug rather than a feature

**Comment by nickwelp** [comment]
In my case, 
```
const Title = styled.h2`
  font-size: 20px;
  color: ${({ theme }) => theme.colors.darkGrey};
  height: 38px;
  font-size: 28px;
  font-weight: 300;
  line-height: 38px;
  margin-bottom: 20px;
  margin-left: 20px;
  width: calc(100% - 20px);
  padding: 0;
`;


const PageTitle = styled(Title)`
        text-align: center;
`;
```



Doesn't work; nor does using && change anything. Text-align: center doesn't show up in any style sheets as rendered in my FireFox browser. For me, it's as if the PageTitle stylesheet is never built. Furthermore there is no prior text-align competing with it.

**Comment by nickwelp** [comment]
In my case, though the style is generated:
```
.jrJmTH{text-align:center;color:red;}
```

The actual element is not assigned that class:
```
<h2 class="sc-brqgnP dQcFTS">Add New User</h2>
```

**Comment by seeden** [comment]
Same issue in the latest code

**Comment by probablyup** [comment]
Going to lock this as the OP issue has been resolved. Please make a new issue with reproduction if necessary.
