### ISSUE TITLE
Creating keyframes using styled objects

### ISSUE THREAD

**Issue by theetrain** [styled-components/styled-components#2561]
Hello, thank you for maintaining Styled Components.

I would like to echo the sentiment shared in this [Spectrum thread](https://spectrum.chat/styled-components/help/how-can-i-use-a-custom-animation-with-the-style-object-syntax~91d624ea-a5a3-4d0e-9314-4da860059112): creating custom animations using styled objects. This is something I would like to use in styled-components.

Here is an example using styled objects with `keyframes`, but requiring an interpolated string when consuming the animation: https://codesandbox.io/s/animation-objects-b6h6h

```jsx
const animation = keyframes({
  from: {
    opacity: 0
  },
  to: {
    opacity: 1
  }
})

// Keyframes must be consumed as an interpolated string 
const Component = styled.div`
  animation: ${animation} 3s;
`
```

Please let me know if there's anything I can do to assist.

**Comment by probablyup** [comment]
PRs welcome

**Comment by mydesireiscoma** [comment]
@theetrain 
I found the way, how to solve your problem without making changes in styled-components

```js
import styled, { keyframes, css } from 'styled-components'

const fadeIn = keyframes`
  0% {
    opacity: 0;
  }
  100% {
    opacity: 1;
  }
`
export const Test = styled.div({
  animation: () => css`${fadeIn} 1s linear infinity`
})
```

Enjoy! Hope it works for you.
I tested code above by myself and everything works like a charm

**Comment by carleryd** [comment]
@Grsmto I've had the same experience today using version 5.2.1.
I'm new to styled-components so if someone can confirm that'd be great!

**Comment by pvarga-dni** [comment]
By the way, this is how a template string (for the animation) and a style object for the rest can be used together: (forked from the example above): https://codesandbox.io/s/animation-objects-forked-cwwn4

**Comment by kitten** [comment]
Resolved in #3469 and #3497

**Comment by pgonzalez-santiago** [comment]
Hi, I am using the latest version 5.3.1 and although this works:

```js
const animation = keyframes({
  from: { opacity: 0 },
  to: { opacity: 1 }
});

const Animated = styled.div({
  animation: css`
    ${animation} 1s infinite
  `
});
```

this does not:
```js
const Animated2 = styled.div(({time = 1}) => ({
  animation: css`${animation} ${time}s infinite` 
}))
```

I was trying it here: [Codesandbox example](https://codesandbox.io/s/test-animation-styled-components-ktl31?file=/src/App.tsx:262-363)

I saw this was solved in this [PR](https://github.com/styled-components/styled-components/pull/3497/files) but there are no tests with functions.

**Comment by carpben** [comment]
Still doesn't work for me. Using it within a media query nested object. 
#3469 doesn't seem to solve such a case. Perhaps issue should be reOpened?
