### ISSUE TITLE
StyleSheetManager on the SSR ( FOUC )

### ISSUE THREAD

**Issue by ROUDALI** [styled-components/styled-components#2799]
Hi everyone , i'm using StyleSheetManager in a Next.js project in order to call stylisRTLPlugin
example : (i'm using styled_components in componentStepper )

example : https://codesandbox.io/s/hello-world-1urec 
**GO to** https://1urec.sse.codesandbox.io/about **and start refreshing the page === (FOUC)**

the problem is when i load the page in first ms it shows the page without style , then the style is loaded.
Anyone one please know how can i solve this problem , Thank's :)

_Originally posted by @ROUDALI in https://github.com/styled-components/styled-components/issues/2794#issuecomment-540485490_

**Comment by samsam-ahmadi** [comment]
Hi, @ROUDALI  
you must add styled like a child in the header at   _document.js

`<Head>{this.props.styleTags}</Head>`

**Comment by ROUDALI** [comment]
it's already added on our project, I added it in sandbox example but still has same behaviour :/

**Comment by Lyncee59** [comment]
Hey, I have the exact same problem with the v5 compared to the v4, styles are not originally picked up on the server side rendering for the initial html document load. I am using as well the ServerStyleSheet inside the getInitialProps hook from NextJS.

**Comment by Lyncee59** [comment]
yes still same problem, I was hoping one of the next patches would fix it (love the perf improvements)

**Comment by Lyncee59** [comment]
@ROUDALI I fixed my missing style problems, main reason was that my Layout component was wrapping <Component /> in the custom <App /> and the layout style was not picked up anymore with the latest version during the SSR. Moved my <Layout /> inside each page component and it solved the issue.

**Comment by aganglada** [comment]
I still have the same problem, missing styles on the server, styles on the client.
I'm not using next.js tho.

On the server: 

```
<StyleSheetManager
   stylisPlugins={features.ft_rtl ? [stylisRTLPlugin] : null}
   sheet={sheet.instance}
 >
   <HelmetProvider context={helmetContext}>
       <App> // inside app there is a Layout component
           {routes}
        </App>
   </HelmetProvider>
</StyleSheetManager>
```

On the client (same thing without `sheet` prop):

```
<StyleSheetManager
   stylisPlugins={features.ft_rtl ? [stylisRTLPlugin] : null}
 >
   <HelmetProvider context={helmetContext}>
       <App> // inside app there is a Layout component
           {routes}
        </App>
   </HelmetProvider>
</StyleSheetManager>
```

Is there anything I'm doing wrong?

**Comment by probablyup** [comment]
My guess is there are multiple versions of s-c in use on the server/client - please ensure only a single version is installed via yarn's "resolutions" feature and then report back.

**Comment by aganglada** [comment]
I will check that out. Thanks @probablyup

**Comment by probablyup** [comment]
Just updated to the new RC for v5 and stylis-plugin-rtl, things seem to be happy now: https://codesandbox.io/s/hello-world-8zlb6

**Comment by ROUDALI** [comment]
@probablyup thank's for your answer, yes true there is no FOUC anymore ,  i don't if you noticed that the ltr style still flashing when you refresh the page, thank's again

**Comment by probablyup** [comment]
@ROUDALI updated my sandbox, there was some bad code in there (improper DOM nesting, and also some legacy next stuff that was sending warnings). appears to be fine: https://codesandbox.io/s/hello-world-8zlb6

**Comment by ROUDALI** [comment]
thank's :)
