### ISSUE TITLE
createGlobalStyle adds stylings to the <head> twice in 5.0.1

### ISSUE THREAD

**Issue by natterstefan** [styled-components/styled-components#3076]
## Environment

- `react@16.12.0`
- `react-dom@16.12.0`
- `react-scripts@3.0.1`
- `styled-components@5.0.1`

⬇️ see codesandbox example.

## Reproduction

- [codesandbox - buggy w/ styled-components@5.0.1](https://codesandbox.io/s/epic-firefly-gzdfx)
- [codesandbox - working w/ styled-components@4.4.1](https://codesandbox.io/s/icy-sun-s88db)

## Steps to reproduce

Open the provided [codesandbox](https://codesandbox.io/s/epic-firefly-gzdfx) and inspect the styling of either of the headlines. The `h1` (or `h2`) styling is applied twice because it was added twice to the document.

If you downgrade styled-components ([see codesandbox](https://codesandbox.io/s/icy-sun-s88db)) to the latest 4.x.x version and inspect the elements again, everything is fine.

## Expected Behavior

Global style is added only once.

## Actual Behavior

Global style is added twice to the document (also in a SSR scenario, which happens in one of our apps right now).

### Bug with version 5.0.1

![image](https://user-images.githubusercontent.com/1043668/77751757-95a66680-7026-11ea-8fe6-9184a7222fe3.png)

### Working w/ version 4.4.1

![image](https://user-images.githubusercontent.com/1043668/77751779-9fc86500-7026-11ea-90ff-812594a44392.png)

**Comment by bfields-cpi** [comment]
Seeing the same doubling of styles created with `createGlobalStyle` on v5.1.0.
Gentle bump ;)

**Comment by EduardAkhmetshin** [comment]
Global styles are rendered twice because of React.StrictMode, so you won't have this issue in production mode. I provided a pull request to solve this.

**Comment by dilipp02** [comment]
Issue still exists and its annoying

**Comment by lakaniemi** [comment]
This is indeed caused by `React.StrictMode`, with more details described by @EduardAkhmetshin in his PR #3121. The issue is quite annoying, but I managed to work around it by moving `ThemeProvider` and the global CSS component outside of `React.StrictMode`. Not the most ideal solution, but I guess the biggest benefit of `React.StrictMode` is finding faults in your own code, and thus it shouldn't matter that it's deeper in the component tree after all the providers :)

**Comment by Silon** [comment]
@natterstefan I solve this problem by moving GlobalStyle outside React.StrictMode:

```
ReactDOM.render(
  <>
    <GlobalStyle />
    <React.StrictMode>
      <ThemeProvider theme={theme}>
        <Provider store={store}>
          <ConnectedRouter history={history}>
            <App />
          </ConnectedRouter>
        </Provider>
      </ThemeProvider>
    </React.StrictMode>
  </>,
  document.getElementById("root")
);

**Comment by kitten** [comment]
I think this was resolved a while ago. See: https://github.com/styled-components/styled-components/blob/d96101a102b59a8f9ac4b6f278594674897282bb/packages/styled-components/src/constructors/createGlobalStyle.ts#L58-L61

**Comment by omBratteng** [comment]
@kitten if using Next.js and strict mode, you'll still get the stylings twice.

**Comment by kitten** [comment]
@omBratteng I mean, that'd then be a Next.js issue. If you look at the code above the important thing to note is that on the client-side we have an effect that properly inserts the styles. So the synchronous logic that could in theory duplicate is isolated to just the server-side code. I'm not sure, but I don't think strict mode even applies to server-side rendering. However, if it does I'd take that as Next.js issue, as I don't think it necessarily should 😅

**Comment by omBratteng** [comment]
Next.js doesn't run strict mode on the server side, if I'm not mistaken.
I did some fiddling edited `styled-components.cjs.js` and replaced https://github.com/styled-components/styled-components/blob/d96101a102b59a8f9ac4b6f278594674897282bb/packages/styled-components/src/constructors/createGlobalStyle.ts#L53 with https://github.com/styled-components/styled-components/blob/d96101a102b59a8f9ac4b6f278594674897282bb/packages/styled-components/src/constructors/createGlobalStyle.ts#L58-L61 (and used useEffect instead), it doesn't render twice

**Comment by kitten** [comment]
@omBratteng It's possible that Next.js resolves the client-side bundle only 🤷 As you can see there, it's guarded by `__SERVER__`. If you mean on the client-side then that's not really possible, however, server-side, that may be caused by this. This may change though / be coincidentally fixed with: https://github.com/styled-components/styled-components/pull/3551

**Comment by MahmoodBawazir** [comment]
Having this exact same issue using Razzle.js too. Does anyone know any workarounds?

**Comment by edarioq** [comment]
Getting this issue, renders twice, and also it overrides a components' styles.
