### ISSUE TITLE
Same classname applied in SSR

### ISSUE THREAD

**Issue by vijayaganthF22** [styled-components/styled-components#3125]
I have created my environment Next JS with styled component. 
1. Some first time style appear not properly, after refresh only render correctly.
2. Same classname is appear different HTML tag.

So if it's appearing same classname total page will collapse

<img width="518" alt="Screenshot 2020-04-28 at 5 38 42 PM" src="https://user-images.githubusercontent.com/61178007/80485614-5f3a6f00-8977-11ea-8c66-1adf3650fa24.png">

**Comment by koellcode** [comment]
@vijayaganthF22 do you have a minimal github repo or codesandbox sample to reproduce this?

**Comment by brendanmoore** [comment]
@koellcode @vijayaganthF22 I am also having this issue with SSR and rehydration in production mode (again no nextjs). Issue only occurs using SC 5.0

**Comment by bozskejkaja** [comment]
I'm having this issue using Next.js & SSR, and another issue that seems related too.
![image](https://user-images.githubusercontent.com/19172849/81685844-83f31400-9458-11ea-8ce7-d2084e7a44ce.png)
It seems to be unrelated as to whether the babel plugin has `displayName` set to `true` or `false`.
I've also noticed a similar mismatch in props I'm passing to a styled component:
![image](https://user-images.githubusercontent.com/19172849/81686311-bf8dde00-9458-11ea-88fc-8ffd8998fd76.png)
![image](https://user-images.githubusercontent.com/19172849/81686613-e64c1480-9458-11ea-837a-23e8aad263d6.png)

Another thing I've noticed is that whenever the app hot reloads, the classes & props get re-applied correctly. That's unfortunately not very helpful in a production build, where this is the biggest pain point.

I'm sure this was not an issue pre-Styled-Components 5.0. Not very clear on when it started though. Any ideas on workarounds in the meantime? 🙏

**Comment by sumanbh** [comment]
Could this be related to NODE_ENV somehow? Seeing this issue if I set NODE_ENV to `production`. However, if I change it to anything else, it seems to render correctly.

**Comment by inestavares** [comment]
Bumping as we are seeing this exact same issue, but we are still on SC 4.4.1 - no `nextjs` either. 
Like @bozskejkaja we see this when using conditional checks around components and only when it hydrates - the initial server render is correct. Has anybody found the root cause for this? 

Changing the NODE_ENV is unfortunately a complicated workaround for us.

**Comment by brendanmoore** [comment]
@inestavares I only had the issue on SC5+ reverting to SC 4.4.1 didnt show the issue. Unfortunately I haven't had the time to attempt to create a failing test case

**Comment by tonycassara** [comment]
Having the same issue but specifically in non-dev environments. Local machines have no collisions when running dev and prod builds but as soon as it hits our testing environment we have this issue. Tried replicating the testing environment as much as possible on our machines but can't get the error to occur.

**Comment by idDemonov** [comment]
I have the same problem. The problem starts to appear with version `5.0.0-rc.3`
This works fine on version `5.0.0-rc.2` and below.

**Comment by gladenjoy** [comment]
I have same issue.
version is 5.1.1 and only happen with `NODE_ENV=production`.

Is there a workaround other than changing NODE_ENV?

**Comment by LBRDan** [comment]
+1 Same here with 5.1.0
For me version `5.0.0-rc.2` still have this issue. Had to downgrade to `4.4.1` as @brendanmoore and @inestavares said to make this work.

It seems that could be something related to componentIds and parentIds generation when style collection occurs server side upon a different client hydration/render root component

Maybe from `4.4.1` to `5.1.1` something about the id generation went towards having the id calculated based on the component hierarchy instead of maybe a Native/DOM component perspective (guessing...)

**Comment by tonycassara** [comment]
FYI we downgraded because of this.

**Comment by sumanbh** [comment]
If you're using [webpack-node-externals](https://github.com/liady/webpack-node-externals) with an external library that has a peer-dependency on styled-components, you can try adding that library to `allowlist` (or `whitelist` in old versions) which then bundles the library for server builds and see if that fixes the issue.

**Comment by brendanmoore** [comment]
See also:
https://github.com/styled-components/babel-plugin-styled-components/issues/277
https://github.com/styled-components/babel-plugin-styled-components/issues/291

**Comment by Mattese** [comment]
We have same issue. https://github.com/styled-components/styled-components/issues/3230

**Comment by ludwighogstrom** [comment]
Any updates on this? We're also stuck on 4.x.x because of this issue. As mention above: happens when building with `NODE_ENV=production`.

**Comment by wubobuaa** [comment]
same issue.only happen when NODE_ENV=production

**Comment by chrkulbe** [comment]
Hi @all,
I've stuck into the same problem and analysed it.

I think, this is the problem:
https://github.com/styled-components/styled-components/blob/a8507e6ac7267e3d74b08b457ced58d182b49515/packages/styled-components/src/models/ComponentStyle.js#L69
After manually adding this line to the production build, all errors are resolved.

Maybe I've a different scenario because I using my own defined styled component Mixin/HOC like this:
```javascript
type VisibleAttrs = { visible?: boolean };
export const Visible = <C extends AnyStyledComponent>(
    element: C,
): StyledComponent<
    StyledComponentInnerComponent<C>,
    DefaultTheme,
    StyledComponentInnerOtherProps<C> & VisibleAttrs,
    StyledComponentInnerAttrs<C>
> => styled(element).attrs<VisibleAttrs>((props) => ({
    'aria-hidden': props.visible === false,
}))<VisibleAttrs>`
    ${(props) => {
        return (
            props.visible === false &&
            css`
                display: none;
            `
        );
    }}
`;
```
It only adds display:none and aria-hidden if props.visible === false.

But it is used on many styled components such as:
```javascript
export const SCContent = Visible(styled.div`
    display: grid;
    grid-row: 3;
    padding: 2rem;
`);
```
or
```javascript
export const SCContainer = Visible(styled.div``);
```

This results in
```html
class="Contentcss__SCContent-wlss8h-0 Visiblemixin__Visible-sc-4z0g1d-0 KIzlc"
```
or
```html
class="Containercss__SCContainer-1r93u80-0 Visiblemixin__Visible-sc-4z0g1d-0 KIzlc
``` 

The visible classNames are generated correctly because I'am using the Visible Mixin styled component and the original component based styled component, but the effective hash is not updated. It's always based on the outer styled component and this is the Visible Mixin and is only updated in a **none** production environment.

**Comment by chrkulbe** [comment]
> Any updates on this? We're also stuck on 4.x.x because of this issue. As mention above: happens when building with `NODE_ENV=production`.

No comments / hints from the developers?

**Comment by thilohaas** [comment]
is there any workaround apart from downgrading to v4?

**Comment by ludwighogstrom** [comment]
> is there any workaround apart from downgrading to v4?

Might remember wrong but think the problem disappeared when `displayName` was set to `true` in babel config (see https://styled-components.com/docs/tooling#better-debugging) ...did not investigate so thoroughly (it was not an option for prod in my case).

**Comment by jsphkhan** [comment]
Any updates on this? With SC v5, I want to make use of very good RTL support, but this issue is restricting me. Just to update @ludwighogstrom and @idDemonov - both solutions described by you do not work. 
What works? - you have to downgrade to `4.4.1`
And with the downgrade, I cannot make use of RTL support with `stylis-rtl-plugin`

**Comment by Andrew-de-Ridder** [comment]
Same here. We are now making use of shouldForwardProp (for AMP compatibility) and so can’t easily downgrade but we are encouraging this issue randomly.

**Comment by Oikio** [comment]
Same problem here, only happens on ssr. The only way to temporary mitigate it is to use another HTML element, like article instead of div. Tried to resolve it on library level, no luck so far. But it's a real deal breaker and big problem.

**Comment by ryandrewjohnson** [comment]
> Same problem here, only happens on ssr. The only way to temporary mitigate it is to use another HTML element, like article instead of div. Tried to resolve it on library level, no luck so far. But it's a real deal breaker and big problem.

Confirmed this works, but agree this is a big issue. Is there any active development being done on a solution?

**Comment by lpkvadim** [comment]
Any news about this problem?

**Comment by jonkwheeler** [comment]
Going to add to the pile. This issue has prevented me from upgraded all our stacks and design system from v4.4.1 to v5. Now with v6 coming out, I fear we'll be stuck left behind and forced to switch to a new library all because of something that seems small, but isn't.

It **fails** on:
- Next.js 10.0.5
- Styled-Components **5.2.1**
- React 17.0.1

It **succeeds** on:
- Next.js 10.0.5
- Styled-Components **4.4.1**
- React 17.0.1

_This issue only occurs on `production`, thus making it even worse to try and debug._

**Comment by baraeb92** [comment]
Last I heard @kitten need more details and investigation related to this. 

https://github.com/styled-components/styled-components/issues/3230#issuecomment-681841726

**Comment by ltroller** [comment]
Having the same issue with an internal library and the projects using it. 
I understand we are providing little to no details but it is extremely difficult to debug since it only happens in production after building.

**Comment by GrosfeldEzekiel** [comment]
I have the same issue with nextJS.

fails on:

Library | Version
-- | --
Next.js | 10.0.6
Styled-Components | 5.2.1
React | 17.0.1

works on:

Library | Version
-- | --
Next.js | 10.0.6
Styled-Components | 4.4.1
React | 17.0.1

Only happens on production

**Comment by AngelAngelides** [comment]
This seems to happen to our project a lot when we conditionally render components. Like when I have the following inside a container, the components after will have seemingly randomly wrong class names.

```
 {boolean && (
      <StyledComponent props={...props}/>
  )}
```
We are using next.js 9.5.5 and styled components 5.2.1

**Comment by faberyx** [comment]
Having exactly the same issue with Gatsby SSR too, only on production build. Sometimes a component in a page randomly starts rendering  with styles of another one, even if there were no changes in the page.

Using styled components 5.2.1, react 16.13.1, gatsby 2.32.3

**Comment by awinogrodzki** [comment]
Hello,

I have found a potential temporary fix for the issue. 

I am using Next.js ^10.0.1, but the fix should be framework-agnostic.

First of all, install latest SSR compatible version of styled-components:

```
yarn add styled-components@5.2.1 
```

Latest version, 5.2.2 faces [ReferenceError: window is not defined](https://github.com/styled-components/styled-components/issues/3444) error upon server-side rendering. You can track the status of the issue here: https://github.com/styled-components/styled-components/issues/3444

It looks like adding `.withConfig({ componentId: "SOME-UNIQUE-ID" })` to the component whose class name is being duplicated and attached to the wrong component fixes the issue. Eg:  

```tsx
const Content = styled.div.withConfig({
  componentId: 'DrawerContentComponent' // pass unique componentId
})`
  min-height: 100%;
  display: flex;
  flex-direction: column;
`;
```

**Warning:**

[styled-components docs](https://styled-components.com/docs/api) do not mention **componentId** property in object passed to withConfig method. Therefore it should be treated as private and could break in the upcoming releases.

**TypeScript users**

For the same reason as mentioned above `@types/styled-components` do not define **componentId** config property, which requires type-casting to `any`:

```tsx
const Content = styled.div.withConfig({
  componentId: 'DrawerProviderContent',
} as any)`
  min-height: 100%;
  display: flex;
  flex-direction: column;
`;
```

**Comment by awinogrodzki** [comment]
This pull request might be connected with the bug: https://github.com/styled-components/styled-components/pull/2936/files

The problem appeared between 5.0.0-rc.3 (30.12.2019) and 5.0.0-rc.2 (12.11.2019). The above request contains some significant changes to the hashing functionality. Could not prove experimentally though because of pretty complicated setup.

**Comment by jonkwheeler** [comment]
You could be onto something here @awinogrodzki. `hash.js` used to be called `hasher.js` (for context). 

[hasher.js -> hash.js](https://github.com/styled-components/styled-components/commit/cd3ef89673f892f513ccc8e4279a6025261a1c23#diff-a2765f86e9b3741988f5008f38acc5a8595d2880beca7b0cb67b09d6f008ecd8)

_Originally_ this `hasher.js` file was using `generateAlphabeticName` to make the `hash`, like so.

```js
const hasher = (str: string): string => {
  return generateAlphabeticName(hash(str));
};
```

This is also the exact same code that `generateComponentId.js` uses, which is what `createGlobalStyle.js` uses, [shown here](https://github.com/styled-components/styled-components/blob/master/packages/styled-components/src/constructors/createGlobalStyle.js#L22).

It does appear that the [last commit on hash.js](https://github.com/styled-components/styled-components/commit/216f03deb084b8c8c8980a35e25924457ff8f6e4#diff-a2765f86e9b3741988f5008f38acc5a8595d2880beca7b0cb67b09d6f008ecd8) was attempt to resolve some SSR issues.

**Comment by brendanmoore** [comment]
I have tried at least 2 attempts to create a test repo from scratch that can reliably reproduce this issue but really struggled and gave up. 

My gut feeling is that the result of the hashing is creating collisions but so far I have been unable to prove it reliably, if anyone has or can share a repo that can reproduce the issue it will be a great help.

**Comment by eortiz-addi** [comment]
Any update about this issue guys? Same problem here.

**Comment by alete8** [comment]
Something new? I have the same problem here.

**Comment by Petermhen** [comment]
Same problem. Using Gatsby JS with Styled components latest version 5.2.3. Updated from another 5.x version on getting this error. Works in local development mode but in on Netlify or Gatsby Cloud production build my slider's container class is assigned to my navbar's container, thus breaking the navbar. 

This was driving me nuts trying to get to the bottom of the cause. I'm also using SASS so wasn't sure if that was the cause, but given everyone else's reports here matches my experience I suppose Styled Components is at fault.

**Comment by eortiz-addi** [comment]
> Any update about this issue guys? Same problem here.

I'm using:
`"next": "10.0.3"`
`"react": "16.8.6"`
`"styled-components": "^5.2.1"`

I fixed the problem, by creating an `.babelrc` file in my project folder with the follow config

```
{
    "presets": ["next/babel"],
    "plugins": [
        [
            "styled-components", { 
                "ssr": true,
                "displayName": true 
            }
        ]
    ]
}
```

**Comment by Petermhen** [comment]
> Same problem here, only happens on ssr. The only way to temporary mitigate it is to use another HTML element, like article instead of div. Tried to resolve it on library level, no luck so far. But it's a real deal breaker and big problem.

This fixed it for me. 

Even with the older 4.4.1 styled components I'm having the same problem. 

Calling the "withConfig" function and setting the componentId as  @brendanmoore  describes did nothing in my case also.

My setup:
"gatsby": "^3.2.1",
"styled-components": "^5.2.3" (doesn't work with 4.4.1 either)
"gatsby-plugin-styled-components": "^4.4.0",
"babel-plugin-styled-components": "^1.12.0",

**Comment by jmcannon** [comment]
I have the same issue on Next.js. Works on initial render then breaks on first refresh. Setting displayName: true doesn't fix it. This is causing some of my <Wrapper> styled components in different files to generate class names that collide with one another. I can see with displayName: true that the Button <Wrapper> (for example) is getting styled and named with the <Wrapper> of another component. Only way I've found to fix is to change the names of all the Wrappers to be different.

**Comment by Oikio** [comment]
One more update which might help to mitigate (for us it did) or solve this issue:

It doesn't look like hash related issue. **Bug is happening only during rehydration (not during lifecycle) on client side if the list of components' length changes for SSR and CSR.**
 
If instead of `null` you will return let's say an empty `div` for an element which existence might depend on if it's SSR ot CSR, it will render normally, because amount of elements will be preserved.

**Comment by Surajbisht15** [comment]
I found this same issue[here](https://github.com/styled-components/styled-components/issues/3500)
Due to which same css is being applied on both and cause UI breakdown,
Though I have workaround for that and I add a custom class using `className` and add css to that class.
E.g.,
const SomethingStyledComponent = styled.div`
&.className {
// css properties
}
`

**Comment by Alphavader** [comment]
Still having this issue  - only in production and with Gatsby 3

**Comment by jpdrsanchez** [comment]
I have the same issue on NextJS, it works well in the first render, but if I click in a <Link> component, the next page show some elements with the same classnames and only renders correctly after I refresh the page

**fails** on:
Library | Version
-- | --
Next.js | 10.0.8
Styled-Components | ^5.2.1
React | 17.0.1

**works** on:
Library | Version
-- | --
Next.js | 10.0.8
Styled-Components | 4.4.1
React | 17.0.1

This issue only happens on production

**Comment by dejanvasic85** [comment]
Same problem here using Next (production only) and conditional rendering but it's specifically not working for components that are built as part of our Web Component Library. 

Component being inside the node_modules folder, gets ignored when built for server side rendering in the same way that components under src folder are built.

This is evident when using this babel config:

```
{
  "presets": ["next/babel"],
  "plugins": [["styled-components", { "ssr": true, "preprocess": false, "displayName": true }]]
}
```

You'd expect all the components to be respecting the "displayName" property. But inspecting the html output, I can see that the Parent component built in Next has the friendly name class prefix but the inner component (from library) does not.

```
<div
  class="SearchResultsstyles__PaginationWrapper-sc-1wropwu-2 ckrdws"
>
  <div class="sc-ebFjAB itAknn">
    <div class="sc-LKuAh gcuKXG">
      <button aria-label="Previous page" disabled="" class="sc-jzJRlG gSPeNj">
      </button>
      <button aria-label="Next page" class="sc-jzJRlG hGiyCE">
      </button>
    </div>
  </div>
</div>
```

Hopefully this could be helpful in determining the issue which appears to behaving the same as described above.
Thanks

**Comment by oyalhi-mgm** [comment]
We have the same issue only in production. Downgraded to `v4.4.1` and issue went away.

**Comment by mattgperry** [comment]
I also downgraded to `4.4.1` which fixed this completely. I had some luck renaming a component but this is obviously not scalable.

This was on `next@11.0.1`, specifically I could go to a page in production, SSR and hydration would work great, but when I clicked on a link to another page suddenly the same hashed classes would have styles from other components applied, totally breaking the page.

**Comment by mglavall** [comment]
In my case, I fixed it **downgrading the babel-plugin-styled-components to the 1.10.2**. It seems that after that version the displayName property stopped working, and somehow it had something to do with the mixed className problem.

I hope this helps. More info:
https://github.com/styled-components/babel-plugin-styled-components/issues/261

**Comment by kitten** [comment]
This seems like an issue with missing babel-plugin-styled-component's component ID generation. But without a reproduction there's not really something to look at to give a definitive answer. Closing since it's unlikely to yield any useful resolution

**Comment by Crizzooo** [comment]
> Same problem here using Next (production only) and conditional rendering but it's specifically not working for components that are built as part of our Component Library using rollup and typescript.
> 
> Components being inside the node_modules folder, get ignored when built for server side rendering.
> 
> This is evident when using this babel config:
> 
> ```
> {
>   "presets": ["next/babel"],
>   "plugins": [["styled-components", { "ssr": true, "preprocess": false, "displayName": true }]]
> }
> ```
> 
> You'd expect all the components to be respecting the "displayName" property. But inspecting the html output, I can see that the Parent component built in Next has the friendly name class prefix but the inner component (from library) does not.
> 
> ```
> <div
>   class="SearchResultsstyles__PaginationWrapper-sc-1wropwu-2 ckrdws"
> >
>   <div class="sc-ebFjAB itAknn">
>     <div class="sc-LKuAh gcuKXG">
>       <button aria-label="Previous page" disabled="" class="sc-jzJRlG gSPeNj">
>       </button>
>       <button aria-label="Next page" class="sc-jzJRlG hGiyCE">
>       </button>
>     </div>
>   </div>
> </div>
> ```
> 
> Hopefully this could be helpful in determining the issue which appears to behaving the same as described above.

We echo this. The collisions and incorrect class names are only applying to elements we build inside a package of our monorepo. Did you guys find any work around besides downgrading styled components?

**Comment by oyalhi-mgm** [comment]
@Crizzooo yes, the other option for us was to set `babel-plugin-styled-componts` fixed at `1.10.2`. This was we could use the latest version of the `styled-components`

**Comment by dejanvasic85** [comment]
@oyalhi-mgm Yes! This also worked for us!

Here's a good blog post:
https://binyamin.medium.com/solving-the-styled-components-warning-in-next-js-with-babel-83080e45a0ff

Thanks Ben Grunfield.
