### ISSUE TITLE
Custom font doesn't applied with font-family in React Native

### ISSUE THREAD

**Issue by pronevich** [styled-components/styled-components#327]
## Version
1.2.1

## Reproduction

```javascript
import React from 'react'
import styled from 'styled-components/native'

const Container = styled.View`
  flex: 1;
  justify-content: center;
  align-items: center;
`

const Text = styled.Text`
  font-family: 'Custom Font Name';
  font-size: 35;
  text-align: left;
`

export () => 
  <Container>
    <Text>No custom font applied</Text>
    <Text style={{fontFamily: 'Custom Font Name'}}>Custom font applied</Text>
  </Container>
```

## Steps to reproduce

1. Add custom font in project
2. Try to use new font with font-family in styled-components

## Expected Behavior

New font	should be applied with font-family in styled-components

**Comment by mxstbr** [comment]
@jacobp100 as always, any ideas what's going on here? 😉

**Comment by jacobp100** [comment]
Yep! We decided to not allow quotes here, because that would have been a breaking change. There's an open or that fixes this for the next major version.

**Comment by mxstbr** [comment]
Ahh yeah I forgot about that!

**Comment by ghoshabhi** [comment]
Hello @mxstbr ! Can you give a short example of using custom fonts with `styled-components` ?

**Comment by mxstbr** [comment]
This should work: (note the missing quotes around the font name)

```JS
const Text = styled.Text`
  font-family: Custom Font Name;
`
```

----

> Yep! We decided to not allow quotes here, because that would have been a breaking change. There's an open or that fixes this for the next major version.

@jacobp100 we now have a `2.0` branch, would you mind releasing a new major version of `css-to-react-native` and submitting a PR upgrading `styled-components` against `2.0` so that we don't forget?

**Comment by jacobp100** [comment]
I'll get on that!

**Comment by jacobp100** [comment]
Fixed in v2, v1 you'll have to do without quotes. Reopen if you have any issues.

**Comment by DevanandGowda** [comment]
This issue still persists for font names with hyphens, for example

```
const AccordionTitle = styled.Text`
  font-family: Product Sans - Medium;
  font-size: 18px;
`;
```
Will throw `Error: Failed to parse declaration parse "font-family: Product Sans - Medium"`

**Comment by jacobp100** [comment]
Does that work in CSS?

**Comment by DevanandGowda** [comment]
Works when I use inline CSS

style = {{
  fontFamily: "Product Sans - Medium",
}}

**Comment by jacobp100** [comment]
No I mean specifying a font family that contains a dash without using quotes around it

**Comment by DevanandGowda** [comment]
No it doesn't work without the quotes obviously, generally for custom fonts we use `@font-face` for defining the name. For example,

```
@font-face {
    font-family: 'Your - Font - Name'; /*a name to be used later*/
    src: url('http://domain.com/fonts/font.ttf'); /*URL to font*/
}
```

And then use it as -
```
.classname {
    font-family: 'Your - Font - Name';
}
```

**Comment by jacobp100** [comment]
Yeah, thought so. Try adding quotes around your font family

**Comment by DevanandGowda** [comment]
Yes, I have tried adding quotes and it doesn't work. The possible solution right now is to either change the font name or use inline style.

**Comment by jacobp100** [comment]
```js
const AccordionTitle = styled.Text`
  font-family: "Product Sans - Medium";
  font-size: 18px;
`;
```

Will give you,

```js
{
  fontFamily: "Product Sans - Medium",
  fontSize: 18
}
```

If that's not working, double check that font family works when used directly in a stylesheet

**Comment by VelrinBlack** [comment]
I still get error, when I try to use custom font like that:
```css
export const StyledTitle = styled.Text`
  @import url('https://fonts.googleapis.com/css2?family=Poppins:wght@200;400;700&display=swap');
  font-family: Poppins;
`;
```
The error message:
`
fontFamily "Poppins" is not a system font and has not been loaded through Font.loadAsync.
`

**Comment by caner-karaman** [comment]
I have the same issue, 
I use Yantramanav-Regular font family. When i use it inline style or Stylesheet it worked! 
When I used it with styled-components it doesnt work

**Comment by jacobp100** [comment]
Do you have code examples of what you know to work and what you're trying? It's quite hard to help otherwise!

**Comment by Daniel-Cross** [comment]
Getting the same issue:

```
import { Roboto_500Medium, Roboto_700Bold } from "@expo-google-fonts/dev";

export const StyledText = styled.Text`
  font-size: 16px;
  text-align: center;
  color: ${({ colour }) => colour || "#0080ff"};
  padding-top: 5px;
  color: white;
  font-family: Roboto_500Medium;
`;
```

Error message:

`fontFamily "Roboto_500Medium" is not a system font and has not been loaded through Font.loadAsync.`

What is the correct way to import these fonts using styled components? Especially when it's needed in multiple components.

**Comment by jacobp100** [comment]
You need to write

```diff
 import { Roboto_500Medium, Roboto_700Bold } from "@expo-google-fonts/dev";

 export const StyledText = styled.Text`
   font-size: 16px;
   text-align: center;
   color: ${({ colour }) => colour || "#0080ff"};
   padding-top: 5px;
   color: white;
-  font-family: Roboto_500Medium;
+  font-family: ${Roboto_500Medium};
 `;
```

**Comment by Daniel-Cross** [comment]
> You need to write
> 
> ```diff
>  import { Roboto_500Medium, Roboto_700Bold } from "@expo-google-fonts/dev";
> 
>  export const StyledText = styled.Text`
>    font-size: 16px;
>    text-align: center;
>    color: ${({ colour }) => colour || "#0080ff"};
>    padding-top: 5px;
>    color: white;
> -  font-family: Roboto_500Medium;
> +  font-family: ${Roboto_500Medium};
>  `;
> ```

Tried this and it throws up a new error:

![1ADBA25E-EE8D-4D7C-9586-3BB30BD590A1](https://user-images.githubusercontent.com/34304333/111501968-b428d480-8745-11eb-9c73-4b53015d9a86.png)

before it was working but just had a warning.

**Comment by jacobp100** [comment]
Ok, that was unexpected. Try,

```
font-family: "${Roboto_500Medium}";
```

**Comment by Daniel-Cross** [comment]
> Ok, that was unexpected. Try,
> 
> ```
> font-family: "${Roboto_500Medium}";
> ```

New error now.

![Uploading B0E1C294-B78A-4A95-B106-2AD78AB70F18.png…]()

**Comment by jacobp100** [comment]
I think you might need to read the documentation for the font package you're using. It looks like you're meant to use a hook?

**Comment by Daniel-Cross** [comment]
> I think you might need to read the documentation for the font package you're using. It looks like you're meant to use a hook?

Yeah I think this is because I'm not using the `useFonts` hook. However that can only be called in a component body and then applied inline to `Text` components. That means in conjunction with using Styled Components I now have to go to all the components I'm referencing `StyledText` and import the fonts. It's quite messy.
