### ISSUE TITLE
Issue resolving Package/Installation with React-Native CLI

### ISSUE THREAD

**Issue by aarshad786** [styled-components/styled-components#3356]
### System:
 - OS: macOS 11.0.1
 - CPU: (4) x64 Intel(R) Core(TM) i5-5287U CPU @ 2.90GHz
 - Memory: 79.66 MB / 8.00 GB
 - Shell: 5.8 - /bin/zsh
### Binaries:
 - Node: 15.3.0 - /usr/local/bin/node
 - npm: 7.0.14 - /usr/local/bin/npm
 - Watchman: 4.9.0 - /usr/local/bin/watchman

## Steps to reproduce
```shell
npx react-native init myApp
cd myApp
npm install --save styled-components
```
> *Note:* Issue exists with typescript template as well

## Expected Behavior
Package should be installed successfully.

## Actual Behavior
Package Installation failed with the following issue
```shell
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: myApp@0.0.1
npm ERR! Found: react@16.13.1
npm ERR! node_modules/react
npm ERR!   react@"16.13.1" from the root project
npm ERR!   peer react@">= 16.8.0" from styled-components@5.2.1
npm ERR!   node_modules/styled-components
npm ERR!     styled-components@"*" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"17.0.1" from react-dom@17.0.1
npm ERR! node_modules/react-dom
npm ERR!   peer react-dom@">= 16.8.0" from styled-components@5.2.1
npm ERR!   node_modules/styled-components
npm ERR!     styled-components@"*" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /Users/addy/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/addy/.npm/_logs/2020-12-19T17_09_17_410Z-debug.log
```

**Comment by codingdotcom** [comment]
npm version upgrade
and try~~

**Comment by Nitropox** [comment]
Any comment on this? I cannot install styled-components with react native as well without --legacy-peer-deps flag.

**Comment by aarshad786** [comment]
I got an update from someone offline... After updating the npm version it worked.. strange but worked for me

**Comment by Nitropox** [comment]
> I got an update from someone offline... After updating the npm version it worked.. strange but worked for me..

Indeed! I downgraded node version from 15.x to 14.15.4 and it worked as well.

**Comment by sisco931** [comment]
Yea just run npm update and then try again, it should work

**Comment by MaxHa-28** [comment]
> Yea just run npm update and then try again, it should work

This fix doesn't work for me

**Comment by sisco931** [comment]
make sure when your installing these packages that the emulator is not running. for some reason with some packages on some systems, if the emulator is running with the app on it, the package will have an error. this worked for me.

**Comment by MaxHa-28** [comment]
> make sure when your installing these packages that the emulator is not running. for some reason with some packages on some systems, if the emulator is running with the app on it, the package will have an error. this worked for me.

I tried that and it still doesn't work. Nevertheless, thank you for your quick reply.

**Comment by MaxHa-28** [comment]
My bad, I didn't use the latest Version of npm..

Fix:
```
npm install -g npm@latest
npm update
npm install --save styled-components
```

**Comment by sanimridha** [comment]
> > I got an update from someone offline... After updating the npm version it worked.. strange but worked for me..
> 
> Indeed! I downgraded node version from 15.x to 14.15.4 and it worked as well.

this also doesn't work for me😑

**Comment by sanimridha** [comment]
> ## Environment
> ### System:
> * OS: macOS 11.0.1
> * CPU: (4) x64 Intel(R) Core(TM) i5-5287U CPU @ 2.90GHz
> * Memory: 79.66 MB / 8.00 GB
> * Shell: 5.8 - /bin/zsh
> 
> ### Binaries:
> * Node: 15.3.0 - /usr/local/bin/node
> * npm: 7.0.14 - /usr/local/bin/npm
> * Watchman: 4.9.0 - /usr/local/bin/watchman
> 
> ## Steps to reproduce
> ```shell
> npx react-native init myApp
> cd myApp
> npm install --save styled-components
> ```
> 
> > _Note:_ Issue exists with typescript template as well
> 
> ## Expected Behavior
> Package should be installed successfully.
> 
> ## Actual Behavior
> Package Installation failed with the following issue
> 
> ```shell
> npm ERR! code ERESOLVE
> npm ERR! ERESOLVE unable to resolve dependency tree
> npm ERR! 
> npm ERR! While resolving: myApp@0.0.1
> npm ERR! Found: react@16.13.1
> npm ERR! node_modules/react
> npm ERR!   react@"16.13.1" from the root project
> npm ERR!   peer react@">= 16.8.0" from styled-components@5.2.1
> npm ERR!   node_modules/styled-components
> npm ERR!     styled-components@"*" from the root project
> npm ERR! 
> npm ERR! Could not resolve dependency:
> npm ERR! peer react@"17.0.1" from react-dom@17.0.1
> npm ERR! node_modules/react-dom
> npm ERR!   peer react-dom@">= 16.8.0" from styled-components@5.2.1
> npm ERR!   node_modules/styled-components
> npm ERR!     styled-components@"*" from the root project
> npm ERR! 
> npm ERR! Fix the upstream dependency conflict, or retry
> npm ERR! this command with --force, or --legacy-peer-deps
> npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
> npm ERR! 
> npm ERR! See /Users/addy/.npm/eresolve-report.txt for a full report.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /Users/addy/.npm/_logs/2020-12-19T17_09_17_410Z-debug.log
> ```

update your android/build.gradle file version.
>classpath("com.android.tools.build:gradle:4.0.1")

**Comment by correadevuk** [comment]
`yarn add styled-components ` worked for me.

**Comment by aarshad786** [comment]
This was fixed by with npm upgrade. Use the below commands to ensure you have the latest npm installed
```
npm install -g npm@latest
npm update
```

and then run 
```
npm install styled-components
```

**Comment by chenop** [comment]
Got this issue with node 14.17.0 (RN 0.68)
Upgrade to node 14.19.1 solve the issue

**Comment by mgpepe** [comment]
I am still getting that issue with node 16.15.1 and npm 8.11.0

**Comment by iamyahia** [comment]
solution is easy, i have the same problem just run with (--legacy-peer-deps) or run this command:
npm install styled-components --save --legacy-peer-deps

**Comment by inferusvv** [comment]
Isn't it an issue that I need to use `--legacy-peer-deps` flag?
