### ISSUE TITLE
Typescript type checking error about component callback parameter

### ISSUE THREAD

**Issue by Zousdie** [styled-components/styled-components#4052]
## System:
 - OS: Linux 5.15 Debian GNU/Linux 11 (bullseye) 11 (bullseye)
 - CPU: (2) x64 AMD EPYC
 - Memory: 552.62 MB / 2.01 GB
 - Container: Yes
 - Shell: 5.8 - /bin/zsh
## Binaries:
 - Node: 18.15.0 - /usr/local/bin/node
 - Yarn: 1.22.19 - /usr/local/bin/yarn
 - npm: 9.5.0 - /usr/local/bin/npm
## npmPackages:
 - styled-components: 6.0.0-rc.6 => 6.0.0-rc.6 

## Reproduction
https://codesandbox.io/p/sandbox/zen-jepsen-6nhsdm

I'm working on styled-component upgrade, I find an issue about typescript and I created a simple demo about it:
```typescript
import * as React from 'react';
import styled from 'styled-components';

const Test = styled.div`
  color: red;
`;

type TOnClick = React.ComponentProps<typeof Test>['onClick'];

const x: NonNullable<TOnClick> = (e) => {
  e.stopPropagation();
};

const App = () => {
  return (
    <>
      <Test onClick={x} />
      <Test
        onClick={(e) => {
          e.stopPropagation();
        }}
      />
    </>
  );
};

export default App;
```
Typescript cannot correctly infer the param type of the `onClick` of the second Test component. And this example is working in version 5.

## Steps to reproduce
```
> yarn exec tsc

yarn exec v1.22.19
src/App.tsx:19:19 - error TS7006: Parameter 'e' implicitly has an 'any' type.

19         onClick={(e) => {
                     ~


Found 1 error in src/App.tsx:19

error Command failed.
Exit code: 2
Command: tsc
```
<img width="667" alt="image" src="https://github.com/styled-components/styled-components/assets/20764411/c5ecbe17-5fe8-4897-bbd8-29c3c73d8ecb">

## Expected Behavior
Typescript should automatically infer the parameter type of the component's callback.

## Actual Behavior
tsc error

**Comment by paavohuhtala** [comment]
I can confirm this happens with all(?) built-in DOM callbacks in 6.0.0-rc.6. In previous versions TSC is able to infer the types of the callbacks with no issue, but with the latest RC you need to specify the types by hand. Interestingly TypeScript in VS Code is still able to autocomplete the fields from `event`, but the actual type check fails afterwards.

Regardless, this is something that should be included in the test suite (assuming that the tests are type-checked).

**Comment by probablyup** [comment]
I see it and do not understand it. The types look fine to me :/

I've seen bugs like this pop up in other projects, I suspect it's a TS deficiency.

**Comment by Zousdie** [comment]
Today I upgraded the styled-component to version 6.0.0, and tried typescript 4.9.5, 5.0.4 and the latest 5.1.5 respectively, and the above issue still exist.
What confuses me is vscode can give a type hint for `onClick` but infers its parameter `e` as any:
<img width="628" alt="image" src="https://github.com/styled-components/styled-components/assets/20764411/c80661af-8b79-406e-b0cf-d0007ab0bc2f">

**Comment by gineika** [comment]
Same problem:
```js
import styled from 'styled-components'
const Test = styled.div``
export default <Test onClick={(e) => {}} />
```

This error pops up:
```
Parameter 'e' implicitly has an 'any' type.ts(7006)
(parameter) e: React.MouseEvent<HTMLDivElement, MouseEvent>
```

Then updates to this after a second or two:
```
Parameter 'e' implicitly has an 'any' type.ts(7006)
(parameter) e: any
```

**Comment by DustinBrett** [comment]
> What confuses me is vscode can give a type hint for `onClick` but infers its parameter `e` as any

Agreed, I find that quite odd.

**Comment by nnmax** [comment]
Same problem

**Comment by gineika** [comment]
https://github.com/styled-components/styled-components/blob/bb1bd5a80bf46813a2c9b4635399ae04b007c942/packages/styled-components/src/types.ts#L165-L169

This works in my projects:
```js
  Substitute<
    // "as" wins over "forwardedAs" when it comes to prop interface
    Substitute<ForwardedAsTargetProps, AsTargetProps>,
    BaseProps
  >,
```

No other issues. But I didn't test everything.

**Comment by jonaskello** [comment]
Also same problem, tried to upgrade to 6.0 but this issue is blocking the upgrade.

**Comment by winterbe** [comment]
Same problem here. I get 135 errors like these when trying to migrate my project to Styled Components 6.

The problem isn't just related to DOM callbacks but to any function props.

E.g. here's another example to reproduce the issue:

```ts
import React from "react"
import styled from "styled-components"

function MyComponent(props: {hello: (name: string) => string, className?: string}) {
    return <span className={props.className}>{props.hello("world")}</span>
}

const MyStyledComponent = styled(MyComponent)`
    background: pink;
`

function MyApp() {
    return <MyStyledComponent hello={name => `Hello ${name}`}/>
                                     ~~~~
                                     ^ TS7006: Parameter 'name' implicitly has an 'any' type.
}
```

Results o

**Comment by Zousdie** [comment]
This issue has been fixed in version 6.0.4. So close it.

**Comment by ltaylor0510** [comment]
We are still experiencing this issue when upgrading to version 6.1.0. As described by winterbe above, it is happening to any function props, not just those related to DOM callbacks.

**Comment by cahbb** [comment]
I have the same issue in version `6.1.8` 😢

**Comment by ChamaraWP** [comment]
> I have the same issue in version `6.1.8` 😢

Are you able to fix this?
