### ISSUE TITLE
"Warning: Accessing PropTypes via the main React package is deprecated. Use the prop-types package from npm instead"

### ISSUE THREAD

**Issue by williamle8300** [styled-components/styled-components#725]
I'm getting this error. I believe the warning is originating from either:

a) styled-components
b) one of its deps

I'm using `create-react-app` and my only added dep is `styled-components`. Removing `styled-components` makes the warning message go away.

**Comment by nic** [comment]
https://github.com/reactjs/prop-types/blob/master/README.md

**Comment by k15a** [comment]
That's already fixed in master and v2. Just needs to be published.

**Comment by nic** [comment]
Reference: https://github.com/styled-components/styled-components/pull/668

**Comment by rovansteen** [comment]
@k15a this should be fixed in `1.4.5` right? At least that's what the changelog says, still getting the warning tho.

If I look where it's coming from: `styled-components/lib/types.js` which contains the following compiled code:
```
"use strict";

/* todo: I want this to actually be an array of Function | string but that causes errors */
Object.defineProperty(module.exports, "babelPluginFlowReactPropTypes_proptype_GlamorRule", {
  value: require("react").PropTypes.shape({
    cssText: require("react").PropTypes.string.isRequired
  })
});

/* eslint-disable no-undef */
```

**Comment by philpl** [comment]
@rovansteen that explains a lot actually! Thanks!
We should maybe just remove the plugin. As far as I know it's not doing anything for us anyway

**Comment by jeffscottward** [comment]
.... sooo like... you gonna fix it now?

**Comment by philpl** [comment]
@jeffscottward should be fixed with the new version of babel-plugin-flow-react-proptypes in v2 RC

**Comment by kachkaev** [comment]
It’d be great to see a new release in 1.x branch with this fix too. Could anyone please release 1.4.6 please?

**Comment by kolelee4** [comment]
I'm still getting this warning. @jeffscottward How did you get around this?

**Comment by jeffscottward** [comment]
I went through the whole lib folder and replaced the `require('react').PropTypes` with
`var PropTypes = require('prop-types');`
`Proptypes.blahbblah`

Here is the folder zipped up
[styled-components.zip](https://github.com/styled-components/styled-components/files/968962/styled-components.zip)

**Comment by williamle8300** [comment]
@jeffscottward prop not the best idea because the new release will overwrite everything

**Comment by kolelee4** [comment]
@jeffscottward Thank you. @williamle8300 When is the next release?

**Comment by williamle8300** [comment]
I'm not a contributor! Just saying that editing the libs folder is gonna create more headache. Just wait till they decide to cut a release

**Comment by kachkaev** [comment]
@k15a could you please reopen this issue meanwhile and even maybe release `1.4.x`? There must be thousands of devs who see the warning now :smiley: Switching to `v2` until it's stable is something most of us would prefer to avoid.

**Comment by philpl** [comment]
@kachkaev This should be fixed with the 1.4.6 release which has just gone out :smile:

**Comment by jeffscottward** [comment]
@williamle8300 "waiting to cut a realease" is not an option in a production environment. I would appreciate you didn't down vote people who come up with a temporary emergency fix and share it with the community.

**Comment by williamle8300** [comment]
It is an option because builds will silence React's warning logs. Yu can't feel entitled to receive work from the repo controls unless you actually commit work to this repo. Submit a pull request or smthng don't whine.

**Comment by philpl** [comment]
@jeffscottward @williamle8300 As our code of conduct states, we expect respectful conversations amongst members of our community. Please refrain from derogatory remarks. https://github.com/styled-components/styled-components/blob/master/CODE_OF_CONDUCT.md

**Comment by williamle8300** [comment]
@philpl Edited my comment.
